<a href="https://colab.research.google.com/github/Sarvesh-Prajapati/NumPy/blob/main/NumPy_GYM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NumPy**

In [1]:
import numpy as np

In [ ]:
np.__version__   # o/p: '1.26.4'
print(np.__version__)   # o/p: 1.26.4

###**0-D Array**

In [ ]:
arr1 = np.array(42)
arr1  # array(42)
arr1.dtype  # o/p: dtype('int64')

### **1D Array**

In [ ]:
arr2 = np.array((1,2,3,4,5))   # SET of int vals
arr2  #o/p: array([1, 2, 3, 4, 5])
print(arr2)  #o/p: [1, 2, 3, 4, 5]
arr2.dtype  # o/p: dtype('int64')

In [ ]:
ARR = np.array(['Apple', 'Banana', 'Cherry'])
print(ARR.dtype) #O/P: <U6 ; unicode string

In [ ]:
arr3 = np.array([1,2,3,4,5])   # LIST of int vals
# print(arr3)     #O/P: [1 2 3 4 5]
type(arr3) #O/P: 'numpy.ndarray'  ; 'type' returns the class of array
arr3.dtype #O/P: dtype('int64')   ; 'dtype' gives the data type of the array

### **2D Array** -- List of 1D arrays

In [29]:
arr4 = np.array([[1, 2, 3], [4, 5, 6]])
arr4

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
print(arr4)

[[1 2 3]
 [4 5 6]]


In [32]:
for x in arr4: print(x) # Iterating through arr4

[1 2 3]
[4 5 6]


In [ ]:
print(arr4[1][2]) #o/p: 6

In [37]:
for i in range(len(arr4)):        #traverse every 1-D array list of arr4
  for j in range(len(arr4[i])):   #traverse each element in a 1-D array list
    print(arr4[i][j], end = ' ')  #Can also write 'print(arr4[i, j])'

1 2 3 4 5 6 

In [39]:
# NumPy enables traversing in the following way too:
for x in arr4:
  for y in x: print(y, end = ' ')


1 2 3 4 5 6 

### **3D Array** -- List of 2D arrays

In [41]:
arr5 = np.array([[[1, 2, 3],
                  [4, 5, 6]],
                 [[1, 2, 3],
                  [4, 5, 6]]])
arr5

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [42]:
print(arr5)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [43]:
for x in arr5:
  print('x is 2D array:\n', x) #prints 2D list of arr5


x is 2D array:
 [[1 2 3]
 [4 5 6]]
x is 2D array:
 [[1 2 3]
 [4 5 6]]


In [45]:
#-----------TRAVERSAL THROUGH EVERY INTEGER IN arr5
for item in arr5:
  for ele in item:
    for x in ele: print(x, end = ' ')


1 2 3 4 5 6 1 2 3 4 5 6 

In [46]:
#----------- TRAVERSING ANOTHER 3D ARRAY
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:         #using one 'for' loop, 3D array is printed as 2D arrays
  print('x is 2D array:\n', x)

x is 2D array:
 [[1 2 3]
 [4 5 6]]
x is 2D array:
 [[ 7  8  9]
 [10 11 12]]


In [47]:
#-------------------CHECKING DIMENSION OF THE ARRAY
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print('A dim is :', a.ndim)
print('B dim is :', b.ndim)
print('C dim is :', c.ndim)
print('D dim is :', d.ndim)

A dim is : 0
B dim is : 1
C dim is : 2
D dim is : 3


In [ ]:
'''-----------------CREATING HIGHER DIMENSIONAL ARRAYS---------'''

arr = np.array([1, 2, 3, 4], ndmin = 5)
arr                      #O/P: array[[[[[1 2 3 4]]]]]
# for x in arr: print(x) #o/p : [[[[[1 2 3 4]]]]]
print('Number of dimensions :', arr.ndim)  # o/p: Number of dimensions : 5

### **Negative Indexing & Array Slicing**

In [ ]:
#------------ NEGATIVE INDEXING ----------------------

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
arr[1, -1] #O/P: 10
arr[0, -2] #O/P: 4

In [ ]:

#----------------- ARRAY SLICING ------------------------

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])   # [2 3 4 5]
print(arr[4:])    # [5 6 7]
print(arr[:4])    # [1 2 3 4]
print(arr[-3:-1]) # [5 6]
print(arr[1:5:2]) # 2 is the STEP value;  o/p: [2 4]
print(arr[::2])   # [1 3 5 7]

In [ ]:
#----------------- SLICING A 2-D ARRAY -------------------

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4]) #O/P: [7 8 9]
print(arr[0:2, 2]) #O/P: [3 8]

In [66]:
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [ ]:
#----------------- SLICING A 3-D ARRAY -------------------

threeD_arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(threeD_arr[0, 1, 2])   # 6
print(threeD_arr[0, 1, 1:])  # [5 6]
print(threeD_arr[1, 0, :])   # [7 8 9]

### **All data types in NumPy & Characters Used to Represent Them**

```
i - integer, b - boolean, u - unsigned integer, f - float, c - complex float, m - timedelta, M - datetime, O - object, S - string,
U - unicode string, V - fixed chunk of memory for other type ( void )
```

In [ ]:
'''array()' fn can take an optional arg 'dtype' for defining expected data type of array elements'''

arr = np.array([1,2,3,4,5], dtype = 'S')
print(arr)       #O/P: [b'1' b'2' b'3' b'4' b'5']
print(arr.dtype) #O/P: |S1

# For i, u, f, S and U we can define the size as well

arr = np.array([1,2,3,4], dtype = 'i4') # array with data type 4 bytes integer
print(arr) #O/P: [1 2 3 4]
print(arr.dtype) #O/P: int32



In [78]:
# If a type is given in which elements can't be casted, NumPy raises 'ValueError'

arr = np.array(['a', 1, 2, 3], dtype = 'i')
# following stmts WILL NOT execute as above line causes 'ValueError'
print(arr)
print(arr.dtype)

### **astype(): Converting the dtype of existing array**

In [ ]:
# 'astype()' fn creates copy of array, & allows to specify data type as parameter.

arr = np.array([1.1, 2.2, 3.3])
arr.dtype #O/P: float64
newArr = arr.astype('i')  # casting as int32

print(newArr)       #O/P: [1 2 3]
print(newArr.dtype) #O/P: int32

In [ ]:
newArr2 = arr.astype(int)          #converting 'arr' to integers
print(newArr2, ',', newArr2.dtype) #O/P: [1 2 3] , int64

newArr3 = np.array([1, 0, 3])
copyNewArr3 = newArr3.astype(bool)
print(copyNewArr3) #O/P: [ True False  True]
print(copyNewArr3.dtype) #O/P: bool

### **Difference between 'copy' and 'view'**

```
The 'copy' is a new array whereas the 'view' is just a view of the original array.
Copy owns data; any changes made to copy will NOT affect original array, & vice versa.
Any changes made to the view will affect the original array, & vice versa.
```

In [ ]:
arr = np.array([1,2,3])
x = arr.copy()
print(x) #O/P: [1 2 3]
x[1] = 4; print(x) #O/P: [1 4 3]
print(arr) #O/P: [1 2 3] ; arr remains unchanged


arr = np.array([1,2,3])
y = arr.view()
print(arr); print(y) #O/P: [1 2 3]  (for both prints)
y[1] = 4; print(y); print(arr) #O/P: [1 4 3] (for both prints)

### **Attribute 'shape'**

```
'shape' returns a tuple in which each index indicates the no. of elements in each dimension
```

In [ ]:
'''-----------Attrib 'shape' returns a tuple with each index having no. of elements corresponding to each dimension-------'''
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]]) #note that dimensions' lengths (4) are same
print(arr.shape) #O/P: (2, 4) ; means array has 2 dimensions, 1st dimension has 2 elements & 2nd has 4.
ar = np.array([1,2,3,4,5])
print(ar.shape) #O/P: (5,) ; means 5 elements in one dimen of array 'ar'

# x = np.array([[1,2],[3,4,5]]) #here dimensions' len are diff so deprecation warning is generated in o/p
# print(x.shape)

arr1 = np.array([1, 2, 3, 4], ndmin=5)
print(arr1) #O/P: [[[[[1 2 3 4]]]]]
print('shape of array :', arr1.shape) #O/P: shape of array : (1, 1, 1, 1, 4) ; Every integer in o/p implies no. of elements corresponding dimension has.
#In above print's o/p, value 4 at 5th pos means 5th dimension has 4 elements.



### **Attribute 'reshape()'**

In [82]:
'''The 'reshape' attrib adds/removes dimensions or changes no. of elements in each dimension.
One can reshape array in any shape until the elements req for reshaping are equal in both shapes.'''

 #-------------------- Converting 1D array to 2D array ------------------------

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3) # original array is UNCHANGED
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [83]:
newarr2 = arr.reshape(3,4) # original array is UNCHANGED
print(newarr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [84]:
#------------------------ Converting 1D array to 3D array ----------------------------------

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(3,2,2)
print(newarr) #outermost dim has 3 arrays, each in turn contains 2 arrays having 2 elements in each; original array is UNCHANGED

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [85]:
newarr2 = arr.reshape(2,2,3)
print(newarr2) #outermost dimen has 2 arrays, each in turn with 2 arrays having 3 elements in each; original array is UNCHANGED

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [90]:
#----------------- Check if the returned array is a copy or a view -------------------

arr = np.array([1,2,3,4,5,6,7,8])
print(arr.reshape(2,4).base)     # returns original array arr, so it is a view.


[1 2 3 4 5 6 7 8]


### **Unknown Dimension**

```
NumPy allows ONE "unknown" dimen i.e. no need to specify an exact number for ONE of the dimensions in 'reshape' method.
Pass -1 as the value, and NumPy will calculate this number for you.
```

In [95]:
# Convert 1D array with 8 elements to 3D array with 2x2 elements:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr.reshape(2, 2, -1))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
'''----------- FLATTENING THE ARRAY: Converting multi-dimen array to 1D ----------'''

arr = np.array([[1,2,3], [4,5,6]])
print(arr.reshape(-1))    #O/P: [1 2 3 4 5 6]

In [97]:
print(arr) #original array 'arr' unchanged

[[1 2 3]
 [4 5 6]]


### **Iterating through the array**

```
Iterating/traversal is covered above but it's not efficient; it gets slower with increase in no. of dimensions as more
'for' loops are needed. Here, it is done with only ONE for-loop and 'nditer()' fn; works for basic and also higher dim arrays.
```

In [98]:
arr3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]) # 3D array
for x in np.nditer(arr3D):
  print(x, end = ' ')

1 2 3 4 5 6 7 8 

In [99]:
arr2D = np.array([[10, 20], [30, 40]])  # 2D array
for x in np.nditer(arr2D):
  print(x, end = ' ')

10 20 30 40 

In [100]:
arrMulti = np.array([[10, 20], [30, 40], [50, 60, 70]]) #a 2D array with diff (inhomogeneous) sub-array sizes
for x in np.nditer(arrMulti):
  print(x) # generates ERROR

To change datatype of array elements while iterating, use ```op_dtypes = ['expected datatype here']```.

NumPy does NOT change data type of element in-place (where element is in array).

It needs extra space (called buffer) to do so and in order to enable it in ```nditer()```, pass ```flags = ['buffered']```

In [102]:
arr = np.array([1,2,3])
for x in np.nditer(arr, flags = ['buffered'], op_dtypes = ['S']):
  print(x, end=' ')

b'1' b'2' b'3' 

In [103]:
print(arr)
print([x for x in arr])  # arr remains unchanged both in vals and their dtypes

[1 2 3]
[1, 2, 3]


In [104]:
'''Traverse alternate array elements'''

arr = np.array([[1,2,3,4], [5,6,7,8]])
for x in np.nditer(arr[:, : : 2]):
  print(x, end = ' ')

1 3 5 7 

### **Enumerated Iteration:** ```ndenumerate()```

Enumeration means mentioning the sequence number of things one by one. Sometimes we require
corresponding index of the element while iterating, ```ndenumerate()``` can be used for those usecases.

In [105]:
# ---------------- Enumerating through 1D array -------------------------

arr = np.array([1,2,3])
for indx, x in np.ndenumerate(arr):
  print(indx, ' ', x)

(0,)   1
(1,)   2
(2,)   3


If 'indx' in above code is replaced by '*indx', indices would be printed as col of ints.

In [106]:
arr = np.array([1,2,3])
for indx, x in np.ndenumerate(arr):
  print(*indx, ' ', x)

0   1
1   2
2   3


In [109]:
# --------------- Enumerating through 2D array ---------------------

arr = np.array([[1,2], [5,6]])
for indx, x in np.ndenumerate(arr):
  print(indx, ' ', x)

(0, 0)   1
(0, 1)   2
(1, 0)   5
(1, 1)   6


### **Joining NumPy Arrays:** ```concatenate(), stack(), hstack(), vstack(), dstack()```

In [113]:
#-------------------------- concatenate() --------------------------

arr1 = np.array([ [1,2], [3,4] ])
arr2 = np.array([ [5,6], [7,8] ])
arr = np.concatenate((arr1, arr2), axis=1)  # concatenate along columns
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [114]:
arr = np.concatenate((arr1, arr2), axis = 0)  # concatenate along rows
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [116]:
print(np.concatenate((arr1, arr2)))   # default behavior; same as setting 'axis = 0' in above code

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [119]:
#-------------------------- stack() fn --------------------------

# 2D ARRAY EXAMPLE

arr = np.array([[1,2,3], [4,5,6]])
print(np.stack((arr)))

[[1 2 3]
 [4 5 6]]


In [118]:
print((np.stack((arr), axis = 1)))

[[1 4]
 [2 5]
 [3 6]]


In [120]:
# 3D ARRAY EXAMPLE

ar = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
print(np.stack((ar)))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [121]:
print(np.stack((ar), axis = 1))

[[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]]


In [122]:
print(np.stack((ar), axis = 2))

[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]


In [123]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr3 = np.array([7,8,9])

In [125]:
print(np.stack((arr1, arr2, arr3)))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [126]:
print(np.stack((arr1, arr2, arr3), axis = 1))

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [127]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr3 = np.array([7,8,9])

In [128]:
#--------hstack() : stacking along rows; does NOT have an 'axis' arg
print(np.hstack((arr1, arr2, arr3)))

[1 2 3 4 5 6 7 8 9]


In [129]:
#--------vstack(): stacking along cols; does NOT have an 'axis' arg
print(np.vstack((arr1, arr2)))

[[1 2 3]
 [4 5 6]]


In [130]:
#--------dstack(): stacking along depth; does NOT have an 'axis' arg
print(np.dstack((arr1, arr2, arr3)))

[[[1 4 7]
  [2 5 8]
  [3 6 9]]]


### **NumPy Array Splitting**

**For an array of length** 'L' **to be split into** 'n' **sections,** ```array_split()``` **returns** ```L%n``` **sub-arrays of size** ```L//n + 1``` **and the rest of size** ```L//n```.

In [131]:
#------------ Splitting 1D Array ------------
arr = np.array([1,2,3,4,5,6])
print(np.array_split(arr, 4))

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [132]:
print(np.array_split(arr, 3))

[array([1, 2]), array([3, 4]), array([5, 6])]


In [133]:
print(np.array_split(arr, 7))   # no. of sub-arrays (7 here) is greater than len of array arr (6)

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([], dtype=int64)]


In [134]:
#=========== Iterating through the split sub-arrays ==========================

x = np.array_split(arr, 2)
for val in x:
  print(val, end=' ')

[1 2 3] [4 5 6] 

In [135]:
#------------ Splitting 2D Arrays ------------

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
print(np.array_split(arr, 3))

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [143]:
x = np.array_split(arr, 3)
print('x is :', x, '\n')
print('First item is:\n', x[0])

x is : [array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])] 

First item is:
 [[1 2]
 [3 4]]


In [137]:
print(x[0][0], x[0][1])

[1 2] [3 4]


In [138]:
print(x[1])

[[5 6]
 [7 8]]


In [139]:
print(x[1][0], x[1][1])

[5 6] [7 8]


In [144]:
#------------ Another example of 2D array splitting ------------

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
x = np.array_split(arr, 3)

In [145]:
print(x)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [146]:
print(x[0])

[[1 2 3]
 [4 5 6]]


In [ ]:
print(x[0][0]) #O/P: [1 2 3]
print(x[0][0][0]) #O/P: 1

In [147]:
print(np.array_split(arr, 4))

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15]]), array([[16, 17, 18]])]


In [156]:
#--------Example below returns three 2-D arrays (like above one), but they are split along axis=1.
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
x = np.array_split(arr, 3, axis=1)
x

[array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]])]

In [155]:
#------- hsplit() method to split the 2-D array into three 2-D arrays

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
x = np.hsplit(arr, 3)       # vsplit() and dsplit() are also there, dsplit() works ONLY on 3D or higher dimen array
x

[array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]])]

In [154]:
#----------------- vsplit() ----------------

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
x = np.vsplit(arr, 3)
x

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]),
 array([[13, 14, 15],
        [16, 17, 18]])]

### **Searching in NumPy Arrays:** -- where()

In [158]:
# 'where()' returns a TUPLE OF INDICES that have the match for the search in array

arr = np.array([1, 2, 3, 4, 5, 4, 4])
np.where(arr == 4)

(array([3, 5, 6]),)

In [159]:
# Find the indices where the values are even and odd

print(np.where(arr % 2 == 0))
print(np.where(arr % 2 == 1))

(array([1, 3, 5, 6]),)
(array([0, 2, 4]),)


#### **searchsorted()**

```searchsorted()``` **begins search from left/right (if attrib** ```side = 'left'``` **or** ```side = 'right'```**) & returns 1st index where no. is no more/less than next value. Also,** ```searchsorted()``` **is to be used ONLY ON A SORTED ARRAY. Indexing from LHS starts at 0, while from RHS, at 1.**

```Note that this method DOES NOT sort the array.```

In [162]:
# Finding the index (starting frm 0) in array where 5 should be inserted

ar = np.array([1,2,3,3,6,7,8])   # note that the array is sorted, a req for searchsorted() fn
print(np.searchsorted(ar, 5))
print(np.searchsorted(ar, 5, side ='right'))

4
4


In [163]:
br = np.array([6,7,8,8,9,19])
print(np.searchsorted(br, 8))
print(np.searchsorted(br, 8, side ='right'))

2
4


In [164]:
#-------------------- searchsorted() for multiple numbers -------------------------

arr = np.array([1, 3, 5, 7])
x = np.searchsorted(arr, [2, 4, 6])
print(x)

[1 2 3]


### **Sorting NumPy Arrays**

In [ ]:
import numpy as np

In [165]:
arr = np.array([3, 2, 0, 1])
print(np.sort(arr)) #sort() method RETURNS A COPY of array, leaving original array unchanged.

[0 1 2 3]


In [166]:
ars = np.array(['banana', 'cherry', 'apple'])
print(np.sort(ars))

['apple' 'banana' 'cherry']


In [167]:
arb = np.array([True, False, True]) #array of booleans
print(np.sort(arb))

[False  True  True]


In [168]:
arr2D = np.array([[3, 2, 4], [5, 0, 1]])  # 2D array
print(np.sort(arr2D))

[[2 3 4]
 [0 1 5]]


In [169]:
arr3D = np.array([[[2,1], [4,3]], [[6,5],[8,7]]]) #3D array
print(np.sort(arr3D))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### **Filtering NumPy Arrays**

Getting some elements out of an existing array and creating a new array out of them is called filtering. In NumPy, you filter an array
using a boolean index list. A boolean index list is a list of booleans corresponding to indexes in the array.
If the value at an index is ```True``` that element is contained in the filtered array, if the value at that index is ```False```, that element is
excluded from the filtered array.

In [3]:
import numpy as np
arr = np.array([41,42,43,46])
x = [True, False, True, False]
print(arr[x])
print(arr[[False, True, False, True]])

[41 43]
[42 46]


In [4]:
#------ Create a filter array that will return only values higher than 42 ------------

arr = np.array([40, 41, 42, 43, 30, 44, 47])
filter_arr = []
for ele in arr:
  if ele > 42: filter_arr.append(True)
  else: filter_arr.append(False)
newArr = arr[filter_arr]

print(arr)
print(filter_arr)
print(newArr)

[40 41 42 43 30 44 47]
[False, False, False, True, False, True, True]
[43 44 47]


In [6]:
#-------- Above code in another way ----------------------

arr = np.array([40, 41, 42, 43, 30, 44, 47])
filter_arr = arr > 42
newArr = arr[filter_arr]
print(filter_arr)
print(newArr)

[False False False  True False  True  True]
[43 44 47]


In [7]:
#------- Direct way
arr = np.array([40, 41, 42, 43, 30, 44, 47])
print([arr[arr > 42]])
print(*[arr[arr > 42]])
print(*[arr[arr % 2 == 0]]) # ONLY even numbers in array

[array([43, 44, 47])]
[43 44 47]
[40 42 30 44]


# **NumPy Random**

In [ ]:
#Random number does NOT mean a different number every time. Random means something that can not be predicted logically.
# If there is a program to generate random number it can be predicted, thus it is not truly random. # Random numbers generated through a generation
# algorithm are called pseudo random.

'''------------------------------GENERATING RANDOM INTS AND FLOATS -------------'''
from numpy import random
x = random.randint(100) #any random int < 100
print(x)
y = random.randint(100, size=(5)) #random list of array of 5 ints
print(y)
yy = random.randint(100, size=(3, 5)) #3 X 5 2D-array in list of random ints
print(yy)
z = random.rand() #assigns a list of ONE random float no. to z
print(z)
a = random.rand(3) #assigns a list of THREE random float no. to a
print(a)
b = random.rand(3, 5) #3X5 2-D list of random floats
print(b)
'''----------------------------GENERATING RANDOM INTS FROM AN ARRAY: THE choice() METHOD --------------'''
#choice() method takes an array as a parameter and randomly returns one of the values.
x = random.choice([3, 5, 7, 9])
print(x)
y = random.choice([3, 5, 7, 9], size = (3, 5)) #3X5 2D-arrays in list of random no. taken from the array in 'choice' fn
print(y)

'''------------------------------RANDOM DATA DISTRIBUTION------------------------'''
# Data Distribution is a LIST of all possible values, & how often each value occurs. Such lists are imp when working with statistics & data science.
# The random module offer methods that returns randomly generated data distributions.
# RANDOM DISTRIBUTION: A random distribution is a set of random numbers that follow a certain 'probability density function' that describes a continuous
# probability. i.e. probability of all values in an array. We can generate random numbers based on defined probabilities using the choice() method of the
# random module. The choice() method allows us to specify the probability for each value. The probability is set by a number between 0 and 1, where
# 0 means that the value will never occur and 1 means that the value will always occur.

'''Generate a 1-D array containing 100 values, where each value has to be 3, 5, 7 or 9. Specifiy individual probabilities of these nos.'''
from numpy import random
x = random.choice([3,5,7,9], p = [0.1, 0.3, 0.4, 0.2], size = (100)) #probability is represented by 'p' and all its values MUST ADD TO 1.
print(x)
# Printing a randomly distributed 2D array by specifying 'size()' values
x = random.choice([3, 5, 7, 9], p = [0.1, 0.3, 0.4, 0.2], size=(3, 5))
print(x)

'''------------------------------RANDOM PERMUTATION: shuffle() and permutation()------------------------'''
# Permutation is an arrangement of elements, e.g. [3, 2, 1] is a permutation of [1, 2, 3] and vice-versa.
#========Shuffling Arrays: changing arrangement of elements IN-PLACE===============
from numpy import random
import numpy as np
arr = np.array([1,2,3,4,5])
random.shuffle(arr) #shuffle() CHANGES THE ORIGINAL ARRAY
print(arr) #randomly shuffled array printed on every run

x = random.permutation(arr) #this DOES NOT change the original array
print(x) #random permutation of 'arr' is printed; original 'arr' is unchanged
print(arr) # [1 2 3 4 5]

'''----------------------------------------SEABORN LIBRARY-----------------------------------------'''
# Seaborn is a library that uses Matplotlib to plot graphs to VISUALIZE random distributions.
# DISTPLOT or distribution plot takes as input an array and plots a curve corresponding to the distribution of points in array.
import seaborn as sns
import matplotlib.pyplot as plt #pyplot is an object of matplotlib
arr = [-2, -1, 0, 1, 2, 3, 4, 5]
sns.distplot(arr) #distplot() is deprecated & will be removed from Seaborn soon; use displot() or kdeplot()
plt.show()

sns.distplot(arr, hist = False) #'hist=False' turns off historgram printing
plt.show()

'''-------------------------------------------NORMAL DISTRIBUTION (CONTINUOUS)------------------------
Aka Gaussian Distribution (or Continuous Dist.). It fits the probability distribution of many events, eg. IQ Scores, Heartbeat etc. Height of people is
normal dist. as it can be 170, 170.1, 170.11 and so on. The random.normal() method gets a Normal Data Distribution. It has three parameters:
>>loc - (Mean) where peak of bell curve exists  >>scale - (Std Devn) how flat the graph distribution should be. >> size - Shape of returned array.'''
import seaborn as sns
import matplotlib.pyplot as plt
from numpy import random
x = random.normal(loc = 1, scale = 2, size = (2, 3))
print(x)
sns.distplot(random.normal(loc=1, scale=2, size=20), hist = True) #visualizing normal distribution
plt.show()

'''-------------------------------------------BINOMIAL DISTRIBUTION (DISCRETE)------------------------
Aka 'Discrete Distribution', it describes outcome of binary scenarios, e.g. toss of a coin for head/tail. Discrete Distribution is defined
at separate set of events, e.g. a coin toss's result is discrete as it can ONLY be head or tails. It has three parameters:
>>n - no. of trials. >>p - probability of occurence of each trial (e.g. for toss of coin, 0.5 each).  >>size - Shape of the returned array.'''
from numpy import random
import matplotlib.pyplot as plt
import seaborn as sns

x = random.binomial(n=10, p=0.5, size=100) #random bino dist as 1D list of 10 elements; if size = (5, 2), it assigns a 2D array to x
print(x)
sns.histplot(x, kde = True);  plt.show()

sns.histplot(random.binomial(n=200, p=0.5, size=500), kde=True) #distplot() can be used WITH 'hist=True' & 'kde=False'; here, if kde=False, no curve.
plt.show()

#===================Normal & Binomial Distributions Plotted Together
sns.distplot(random.normal(loc=50, scale=5, size=1000), hist=False, label='normal') #set 'kde=True' for plotting a curve too
sns.distplot(random.binomial(n=100, p=0.5, size=1000), hist=False, label='binomial')
plt.legend() #for displaying labels (legends) on plot
plt.show()

'''-------------------------------------------POISSON DISTRIBUTION (DISCRETE)------------------------
Estimates how many times an event can happen in a specified time. e.g. someone eats twice a day what is the probability he will eat thrice?
It has two parameters:   >>lam - rate or known number of occurrences e.g. 2 for above problem.   >>size - The shape of the returned array.'''
from numpy import random
import matplotlib.pyplot as plt
import seaborn as sns

sns.histplot(random.poisson(lam=20, size=10000), kde=True)
plt.show()
#===================Normal & Poisson Dist Plotted Together
sns.histplot(random.poisson(lam=20, size=1000), label='Poisson', kde=True)
sns.histplot(random.normal(loc=20, scale=5, size=1000), label='Normal', kde=True) #if 'lam' and 'loc' values are diff, histograms won't overlap much
plt.legend()
plt.show()

#===================Binomial & Poisson Dist Plotted Together
'''for very large n and near-zero p, binomial dist is near identical to poisson dist such that n*p is nearly equal to 'lam'.'''
sns.histplot(random.poisson(lam=10, size=1000), label='Poisson', kde=True)
sns.histplot(random.binomial(n=1000, p=0.01, size=1000), label='Binomial', kde=True)
plt.legend()
plt.show()

'''-------------------------------------------UNIFORM DISTRIBUTION (DISCRETE)------------------------
It's describes probability where every event has EQUAL chances of occuring. E.g. Generation of random numbers. It has three parameters:
>> a - lower bound (default 0.0)   >> b - upper bound (default 1.0)   >> size - The shape of the returned array'''
from numpy import random
import matplotlib.pyplot as plt
import seaborn as sns

x = random.uniform(size=(2, 3));  print(x) #prints a list of 2D, 2X3 array
sns.histplot(random.uniform(size=1000), kde=True);  plt.show()

'''-------------------------------------------LOGISTIC DISTRIBUTION------------------------
It's used to describe growth. Used extensively in ML in logistic regression, neural networks etc. It has three parameters:
>>loc - mean, where the peak of curve is. Default 0.  >>scale - std devn, flatness of distribution. Default 1.  >>size - shape of returned array.'''
from numpy import random
import matplotlib.pyplot as plt
import seaborn as sns

x = random.logistic(loc=1, scale=2, size=(2, 3)); print(x) #prints a list of 2D, 2X3 array of +VE and sometimes -VE floats
sns.histplot(random.logistic(loc=10, scale=5, size=1000), kde=True); plt.show()

#===================Normal & Logistic Dist Plotted Together
'''Both distribns are near identical, but Log dist has more area under the tails, meaning it represents more possibility of occurrence of an event further
away from mean. For higher value of scale (standard deviation) the normal and logistic distributions are near identical apart from the peak.'''
sns.histplot(random.normal(scale=20, size=1000), kde=True, label='normal')
sns.histplot(random.logistic(scale=20, size=1000), kde=True, label='logistic')
plt.legend(); plt.show()

'''-------------------------------------------MULTINOMIAL DISTRIBUTION------------------------
Multinomial distribution is a generalization of binomial distribution. It describes outcomes of multi-nomial scenarios unlike binomial where scenarios must
be only one of two. e.g. Blood type of a population, dice outcomes. It has three parameters:
>>n - no. of possible outcomes (e.g. 6 for dice)  >>pvals - list of probabilties of outcomes (e.g. [1/6, 1/6, 1/6, 1/6, 1/6, 1/6] for dice roll).
>>size - shape of returned array.'''
from numpy import random
x = random.multinomial(n=6, pvals=[1/6, 1/6, 1/6, 1/6, 1/6, 1/6]);  print(x)
sns.histplot(random.multinomial(n=6, pvals=[1/6, 1/6, 1/6, 1/6, 1/6, 1/6])); plt.show()
sns.histplot(random.multinomial(n=10, pvals=[1/10,1/10,1/10,1/10,1/10,1/10,1/10,1/10,1/10,1/10])); plt.show()

'''-------------------------------------------EXPONENTIAL DISTRIBUTION------------------------
It's used for describing time till next event e.g. failure/success etc. Poisson distribution deals with number of occurences of an event in a time period
whereas exponential distribution deals with the time between these events. It has two parameters:
>> scale - inverse of rate (see 'lam' in poisson distribution above) defaults to 1.0.   >> size - The shape of the returned array.'''
from numpy import random
import matplotlib.pyplot as plt
import seaborn as sns

x = random.exponential(scale = 2, size = (2, 3)); print(x)
sns.histplot(random.exponential(scale = 20, size = 1000), kde = True);  plt.show()

'''-------------------------------------------CHI SQUARE DISTRIBUTION------------------------
It used as a basis to verify the hypothesis. It has two parameters: >>df - degree of freedom  >>size - shape of returned array.'''
x = random.chisquare(df = 2, size = (2, 3)); print(x)
sns.histplot(random.chisquare(df = 2, size = 1000), kde = True); plt.show()

'''-------------------------------------------RAYLEIGH DISTRIBUTION------------------------
It's used in signal processing. It has two parameters: >>scale - std dev, how flat distribution is, default 1.0  >>size - shape of returned array.
NOTE THAT at unit std dev and 2 degrees of freedom, rayleigh and chi square represent the same distributions.'''
x = random.rayleigh(scale=2, size=(2,3)); print(x)
sns.histplot(random.rayleigh(size = 1000), kde=True) ; plt.show()

'''-------------------------------------------PARETO DISTRIBUTION------------------------
It reflects Pareto's law i.e. 20% factors cause 80% outcome). Has 2 parameters: >>a - shape parameter  >>size - shape of returned array.'''
x = random.pareto(a = 2, size = (2, 3)); print(x)
sns.histplot(random.pareto(a = 20, size = 1000), kde = True); plt.show()

'''-------------------------------------------ZIPF DISTRIBUTION------------------------
Zipf's Law: In a collection, nth common term is 1/n times of most common term. E.g. 5th most common word in English occurs nearly 1/5 times as often as
the most common word. It has two parameters:  >>a - distribution parameter.  >> size - The shape of the returned array.'''
x = random.zipf(a = 2, size = (2, 3)); print(x)
y = random.zipf(a = 2, size = 100); print(y)
#Sample 1000 points but plotting only ones with value < 10 for more meaningful chart.
x = random.zipf(a=2, size=1000)
sns.histplot(x[ x < 10], kde = True)
plt.show()


# **NumPy Ufuncs**

In [ ]:
'''ufuncs stands for "Universal Functions" and they are NumPy functions that operate on 'ndarray' object. ufuncs are used to implement VECTORIZATION in
NumPy which is way faster than iterating over elements. They also provide broadcasting and additional methods like reduce, accumulate etc. that are very
helpful for computation. ufuncs also take additional arguments, for example:
>>where - boolean array or condition defining where the operations should take place.
>>dtype - defining the return type of elements.
>>out - output array where the return value should be copied.'''
#VECTORIZATION: Converting iterative statements into a vector based operation is called vectorization. One way to do this (WITHOUT unfuncs) is as ahead:
lis1 = [1, 2, 3, 4]; lis2 = [4, 5, 6, 7]; res = []
for i,j in zip(lis1, lis2): res.append(i + j) #using zip() fn (NO ufuncs USED HERE)
print(res) #[5, 7, 9, 11]
#With a ufunc, we can use the add() fn of NumPy:
import numpy as np
lis1 = [1, 2, 3, 4]; lis2 = [4, 5, 6, 7]
res = np.add(lis1, lis2)
print(res) #[5 7 9 11]
# print(np.subtract(lis1, lis2)) #np.subtract() is another ufunc, for example
'''------------------------------------------CREATING YOUR OWN ufunc--------------------------------------------
To create your own ufunc, you have to define a fn, like you do with normal fns in Python, Next, add it to NumPy ufunc library with the 'frompyfunc()' fn.
This fn takes following args: >>function - name of the function     >>inputs - number of input arguments (arrays)   >>outputs - number of output arrays.'''
import numpy as np
def myAdd(x, y):
  return x + y
myadd = np.frompyfunc(myAdd, 2, 1)
print(myadd([1,2,3,4], [5,6,7,8]))
print(type(myadd)) #<class 'numpy.ufunc'> ; tells 'myadd' is a ufunc
print(type(np.concatenate)) #<class 'function'>

'''-----------------------------------SIMPLE ARTIHMETIC OF unfuncs---------------------------------------------
You could use arith operators + - * / directly b/w NumPy arrays but this section discusses an extension of the same where we have functions that can take
any array-like objects e.g. lists, tuples etc. and perform arithmetic CONDITIONALLY (means that we can define conditions where arith. opern should happen.
All of the discussed arithmetic functions take a 'where' parameter in which we can specify that condition.'''
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])
print('Additions : ', np.add(arr1, arr2)) #[30 32 34 36 38 40]
print('Subtractions : ', np.subtract(arr1, arr2)) #(arr1 - arr2)
print('Multiplications : ', np.multiply(arr1, arr2)) #[200 231 264 299 336 375]
print('Divisions : ', np.divide(arr1, arr2)) #[0.5  0.52380952  0.54545455  0.56521739  0.58333333  0.6] ; arr1 divided by arr2
print('Exponentiations : ', np.power(arr1, arr2)) #'arr1' raised to power 'arr2'
print('Remainders : ', np.mod(arr1, arr2)) #[10 11 12 13 14 15] ; 1st array divided by 2nd array; 'np.remainder()' fn yields same results
print('Quotients & mods : ', np.divmod([10, 20, 40], [3, 7, 8])) #(array([3, 2, 5]), array([1, 6, 0]))
print('Absolutes : ', np.absolute([-1, -2, 1, 2, 3, -4])) #[1 2 1 2 3 4] ; abs() fn too yields same results but it is inbuilt 'math.abs()' & not NumPy

import numpy as np
'''--------------------------------------ROUNDING DECIMALS----------------------------------------------'''
print('Truncation:', np.trunc([-3.5, 3.5])) #[-3.  3.]
print('Truncation using fix() fn:', np.fix([-3.16667, 3.16667])) #[-3.  3.]
print('The around() fn:', np.around([3.46, 3.58, -3.58, -3.40])) #[ 3.  4. -4. -3.] ; around() fn incr preceding digit/decimal by 1 ONLY if >=5
print('Flooring:', np.floor([-3.06, 3.14, 3.667, 3.56])) #[-4.  3.  3.  3.] ; rounds off decimal to nearest LOWER integer
print('Ceiling:', np.ceil([-3.06, -3.99, 3.14, 3.56])) #[-3. -3.  4.  4.] ; rounds off decimal to nearest HIGHER integer

'''--------------------------------------unfunc LOGARITHMS----------------------------------------------
NumPy provides fns to perform log at base 2, e & 10. We can take log for any base by creating a custom ufunc.
All of the log functions will place '-inf' or 'inf' in the elements if log can not be computed.'''
arr = np.arange(1, 11) #arange(1, n) yields an array of [1 ... n-1]
print(np.log2(arr)) #base-2 log of all values in 'arr'
print(np.log10(arr)) #base-10 log of all values in 'arr'
print(np.log(arr)) #base-e log
#=======Logarithm to any base: NumPy doesn't provide fn to take log at any base, use 'frompyfunc()' with inbuilt 'math.log()' with 2 input params & 1 output
from math import log
import numpy as np
nplog = np.frompyfunc(log, 2, 1) #2 inputs, 1 output
print(nplog(100, 15)) #1.7005483074552052 ; base-15 log of 100
print(nplog(100, 10)) #2.0 ; base-10 log of 100
'''---------------------------------------SUMMATIONS------------------------------------------------------------
Addition is done between two args whereas SUMMATION happens over n elements.'''
arr1 = np.array([1, 2, 3]) ; arr2 = np.array([1, 2, 3])
print(np.add(arr1, arr2)) #[ 2 4 6]
print(np.add(np.array([[1,2,3], [4,5,6]]), np.array([[7,8,9], [10,11,12]]))) #adding 2D arrays
'''[[ 8 10 12]
 [14 16 18]]'''
print(np.sum( [arr1, arr2] )) #[12] ; note 'arr1' & 'arr2' are passed in a LIST in sum()
#---------SUMMATION OVER AN AXIS:
#If you specify axis=1, NumPy will sum the numbers in each array.
print(np.sum([arr1, arr2], axis = 1)) #[6 6]
print(np.sum( [ np.array([[1,2,3], [4,5,6]]), np.array([[7,8,9], [10,11,12]]) ]  )) #[78]
#---------CUMULATIVE SUMMATION
print(np.cumsum(np.array([1,2,3,4]))) #[1 3 6 10] ; aka PARTIAL SUMS
# [[1,2,3], [4,5,6]]
print(np.cumsum(np.array([[1,2,3], [4,5,6]]))) #[ 1  3  6 10 15 21] ; 2D-array
print(np.cumsum(np.array([[1,2,3], [4,5,6]]), axis = 1))
'''[[ 1  3  6]
 [ 4  9 15]]'''
print(np.add(np.array([[1,2,3], [4,5,6]]), np.array([[7,8,9], [10,11,12]])))

import numpy as np
'''-----------------------------------------PRODUCTS & CUMULATIVE PRODUCTS------------------------------------------------------------'''
print(np.prod([1,2,3,4])) #[24]
print(np.prod([[1,2], [5,6]])) #[60]
print(np.prod([[3,4], [7,9]] , axis = 1)) #[12 63]
print(np.cumprod([1,2,3,4])) #[1 2 6 24]
print(np.cumprod([[1,2], [5,6]])) #[1 2 10 16]
print(np.cumprod([[3,4], [7,9]] , axis = 1)) #[[3 12] [7 63]]
'''----------------------------------------DIFFERENCES------------------------------------------------------------------
Discrete difference means subtracting two successive elements. E.g. for [1, 2, 3, 4], the discrete difference would be [2-1, 3-2, 4-3] = [1, 1, 1]
To find the discrete difference, use the diff() function.  The opn can be done repeatedly by setting 'n'. E.g. for [1, 2, 3, 4], the discrete difference
with n = 2 would be [2-1, 3-2, 4-3] = [1, 1, 1] , then, since n=2, we do it once more, with the new result: [1-1, 1-1] = [0, 0]'''
print(np.diff([1,2,5,9,4])) #[1 3 4 -5] ; 2-1, 5-2, 9-5, 4-9
arr = np.array([10, 15 ,25, 5]) ; print(np.diff(arr, n = 2)) #[5 -30]
'''-----------------------------------------LCM & GCD--------------------------------------------------------------------------'''
print(np.lcm(2,6)) #lcm() & gcd() each take only 2 numbers
'''reduce() method will use the ufunc, in this case the lcm() function, on each element, and reduce the array by one dimension'''
print(np.lcm.reduce([2,4,6,8,9])) #[72]
print(np.lcm.reduce([[3,4], [7,9]])) #[21 36]
print(np.lcm.reduce([[3,4], [7,9]], axis = 1)) #[12 63]
print(np.lcm.reduce(np.arange(1,11))) #2520

print(np.gcd(36, 54)) #18
print(np.gcd.reduce([12,45,36,81,9])) #3
print(np.gcd.reduce([[12,18], [28,48]])) #[4 6]
print(np.gcd.reduce([[12,18], [28,48]], axis = 1)) #[6 4]

import numpy as np
'''-------------------------------------TRIGONOMETRIC FNS: sine, cos, tan---------------------------------------------
NumPy provides the ufuncs sin(), cos() and tan() that take values in radians and produce the corresponding sin, cos and tan values.'''
print(np.sin(np.pi/2)) #1.0 ; sine (PI/2)
print(np.cos(np.pi/2))
print(np.cos(np.zeros((3,3))))
'''[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]'''
print(np.tan(np.pi/4)) #0.9999999999999999
print(np.deg2rad([90,180,270,360])) #DEGREES TO RADIANS
print(np.rad2deg([1.57079633, 3.14159265, 4.71238898, 6.28318531])) #[ 90.00000018 179.99999979 269.99999998 360.00000016]
#---------NumPy provides ufuncs arcsin(), arccos() and arctan() that produce radian values for corresponding sin, cos and tan values given.-----
print(np.arcsin(1.0)) #1.5707963267948966
print(np.arcsin([1, -1, 0.1])) #[ 1.57079633 -1.57079633  0.10016742]
#---------Calculating HYPOTENUSE
base = 3; perpendicular = 4
print(np.hypot(base, perpendicular)) #5.0

import numpy as np
'''-------------------------------------HYPERBOLIC FNS: sinh(), cosh(), tanh()---------------------------------------------
ufuncs sinh(), cosh() and tanh() take values in RADIANS and produce the corresponding sinh, cosh and tanh values.'''
print(np.sinh(np.pi/2)) #2.3012989023072947
arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])
print(np.cosh(arr))
#--------Numpy provides ufuncs arcsinh(), arccosh() and arctanh() that produce radian values for corresponding sinh, cosh and tanh values given
print(np.arcsinh(1.0)) #0.881373587019543
#Find the angle for all of the tanh values in array:
arr = np.array([0.1, 0.2, 0.5])
x = np.arctanh(arr); print(x) #[0.10033535 0.20273255 0.54930614]
'''--------------------------------------------SET OPERATIONS--------------------------------------------------------'''
#Use 'unique()' fn to find unique elements from any array. E.g. create a set array, but remember that the set arrays should only be 1-D arrays
arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])
x = np.unique(arr); print(x) #[1 2 3 4 5 6 7]
#UNION and INTERSECTION
arr1 = np.array([1, 2, 3, 4]);  arr2 = np.array([3, 4, 5, 6])
print(np.union1d(arr1, arr2)) #[1 2 3 4 5 6]
print(np.intersect1d(arr1, arr2)) #[3 4]; fn's optional arg 'assume_unique' if set 'True' can incr speed; should always be set 'True' when using sets.
#SET DIFFERENCE: subtract the common elements from the 1st array and display the rest of the elements of the 1st array.
print(np.setdiff1d(arr1, arr2)) #[1 2]
print(np.setdiff1d(arr2, arr1)) #[5 6]
#SYMMETRIC DIFFERENCE: To find only the values that are NOT present in BOTH sets, use the setxor1d() method.
print(np.setxor1d(arr1, arr2, assume_unique = True)) #[1 2 5 6]

